version: '3.8'
services:
  database:
    image: postgres:14.3
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: database
    volumes:
      - ./db_postgres:/var/lib/postgresql/data
